## [pandas入门学习](https://blog.csdn.net/weixin_42398658/article/details/82925410)

### 使用Python的列表创建Series

In [4]:
import numpy as np
import pandas as pd

In [3]:
# 使用 list 创建
s1 = pd.Series([1,2,3,4])  # 可以发现索引index默认从0开始进行自动索引
s1

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
# 值属性，可以方便查看Series的值
s1.values

array([1, 2, 3, 4])

In [5]:
# 索引index属性，返回的是索引从开始到结束和间隔的值
s1.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
# 使用numpy的数组进行创建
s2 = pd.Series(np.arange(10))
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [10]:
# 通过字典进行创建
s3 = pd.Series({'1':1, '2':2, '3':3})
print(s3)

print(s3.values)

print(s3.index)

1    1
2    2
3    3
dtype: int64
[1 2 3]
Index(['1', '2', '3'], dtype='object')


In [22]:
# 手动赋值索引
s4 = pd.Series([1,2,3,4], index=['A','B','C','D'])
print(s4)
print(s4.values)
print(s4.index)

# 根据索引取值
print(s4['B'])

# 根据值得范围取值
print(s4[s4>2])

# 把Series转换为字典输出，也就是说可以通过字典创建Series，也可以通过Series转换为字典
dict_ = s4.to_dict()
print(dict_)

A    1
B    2
C    3
D    4
dtype: int64
[1 2 3 4]
Index(['A', 'B', 'C', 'D'], dtype='object')
2
C    3
D    4
dtype: int64
{'A': 1, 'B': 2, 'C': 3, 'D': 4}


In [43]:
# 来回转
s5 = pd.Series(dict_)
print(s5)

# 可单独把索引写出，再赋值给Series，同时多增加一个索引
index_1 = ['A','B','C','D','E']
s6 = pd.Series(s5, index=index_1)
print(s6)

# 根据pd.isnall()判断Series的元素是否有空值，如果有返回Ture，反之False
# 类似的操作 notnull()
print(pd.isnull(s6))

#s6中元素是否比0大
print(s6>0)

A    1
B    2
C    3
D    4
dtype: int64
A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
dtype: float64
A    False
B    False
C    False
D    False
E     True
dtype: bool
A     True
B     True
C     True
D     True
E    False
dtype: bool
