## [NumPy-菜鸟教程](https://www.runoob.com/numpy/numpy-ndarray-object.html)

### [NumPy Ndarray 对象](https://www.runoob.com/numpy/numpy-ndarray-object.html)

创建一个 ndarray 只需调用 NumPy 的 array 函数即可：
`numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
`

|名称|	描述|
|----:|--------:|
|object|	数组或嵌套的数列|
|dtype	|数组元素的数据类型，可选|
|copy	|对象是否需要复制，可选|
|order	|创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）|
|subok	|默认返回一个与基类类型一致的数组|
|ndmin	|指定生成数组的最小维度|

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
a = np.array([[1,2,3], [4,5,6]], ndmin = 3)
print(a)

[[[1 2 3]
  [4 5 6]]]


In [21]:
a = np.array([1,2,3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


### [NumPy 数据类型](https://www.runoob.com/numpy/numpy-dtype.html)

下表列举了常用 NumPy 基本类型。

|名称|	描述|
|----:|-------:|
|bool_|	布尔型数据类型（True 或者 False）|
|int_|	默认的整数类型（类似于 C 语言中的 long，int32 或 int64）|
|intc|	与 C 的 int 类型一样，一般是 int32 或 int 64|
|intp|	用于索引的整数类型（类似于 C 的 ssize_t，一般情况下仍然是 |int32 或 int64）|
|int8|	字节（-128 to 127）|
|int16|	整数（-32768 to 32767）|
|int32|	整数（-2147483648 to 2147483647）|
|int64|	整数（-9223372036854775808 to 9223372036854775807）|
|uint8|	无符号整数（0 to 255）|
|uint16|无符号整数（0 to 65535）|
|uint32|无符号整数（0 to 4294967295）|
|uint64|无符号整数（0 to 18446744073709551615）|
|float_|float64 类型的简写|
|float16|半精度浮点数，包括：1 个符号位，5 个指数位，10 个尾数位|
|float32|单精度浮点数，包括：1 个符号位，8 个指数位，23 个尾数位|
|float64|双精度浮点数，包括：1 个符号位，11 个指数位，52 个尾数位|
|complex_|complex128 类型的简写，即 128 位复数|
|complex64|复数，表示双 32 位浮点数（实数部分和虚数部分）|
|complex128|复数，表示双 64 位浮点数（实数部分和虚数部分）|

#### 数据类型对象 (dtype)

dtype 对象是使用以下语法构造的：

`numpy.dtype(object, align, copy)`
- object - 要转换为的数据类型对象
- align - 如果为 true，填充字段使其类似 C 的结构体。
- copy - 复制 dtype 对象 ，如果为 false，则是对内置数据类型对象的引用

In [23]:
dt = np.dtype(np.int32)
print(dt)

int32


In [25]:
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
dt = np.dtype('i8')
print(dt)

# 字节顺序标注
dt_ = np.dtype('<i4')
print(dt_)

int64
int32


下面实例展示结构化数据类型的使用，类型字段和对应的实际类型将被创建。

In [31]:
# 首先创建结构化数据类型
dt = np.dtype([('age', np.int8)])
print(dt)

# 将数据类型应用于 ndarray 对象
a = np.array([(10,), (20,), (30,)], dtype = dt)
print(a)

# 类型字段名可以用于存取实际的 age 列
print(a['age'])

[('age', 'i1')]
[(10,) (20,) (30,)]
[10 20 30]


In [32]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
